### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by rdagumampan** [22222/CsvTextFieldParser#12]
Hi 222,

I thought this is the only way to reach you :) Just want to thank you for this code snippets. FYI, I have embedded the main .cs files into my project. Feel free to poke around.
https://github.com/rdagumampan/yuniql

Thanks again,
Rodel / Denmark

**Comment by 22222** [comment]
Thanks for the feedback!  Sorry I didn't reply sooner.

It's great to see how someone else is using a library like this.

**Comment by kwerty** [comment]
Also just here to say thanks.
I was at the tail end of a project when I noticed the Microsoft reader was mysteriously swallowing consecutive CRLFs (screwing up the markdown descriptions I was importing). A Google search led me here, and after swapping out the Microsoft library for yours I was back in action and ready to go live. You saved me a lot of mucking round, and I am very grateful :)
