### ISSUE TITLE
This parser doesn't support multiple delimiters

### ISSUE THREAD

**Issue by hjrb** [22222/CsvTextFieldParser#17]
Then you should change the property delimiters to either string or even better char.

**Comment by 22222** [comment]
That's true, this parser only supports a single delimiter.  So it is definitely a misleading design to have the `Delimiters` property defined as an array of strings.

The reason it's defined that way is for compatibility with the [corresponding Microsoft TextFieldParser.Delimiters property](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.fileio.textfieldparser.delimiters?view=net-6.0#microsoft-visualbasic-fileio-textfieldparser-delimiters).  The idea is that you can mostly use this parser as a drop-in replacement for that one (if you only use it for the cases we support, like parsing a standard CSV file).

If we ever broke away from that goal of compatibility with the Microsoft parser, I would definitely remove the `Delimiters` property or replace it with a single `Delimiter` property at that time.
