### ISSUE TITLE
No errorLine is shown when thrown MalformedException

### ISSUE THREAD

**Issue by Krakean** [22222/CsvTextFieldParser#3]
`

       private CsvMalformedLineException CreateMalformedLineException(string message, string errorLine, long errorLineNumber)

        {

            ErrorLine = errorLine;

            ErrorLineNumber = errorLineNumber;

            return new CsvMalformedLineException(

                message: message,

                lineNumber: errorLineNumber

            );

        }

`

Curious, is ErrorLine forgotten here when creating CsvMalformedLineException? Because as I can see you pass only message & lineNumber.

**Comment by 22222** [comment]
Yes, the error line is only available as that class variable on the parser.

Originally I did have the line included in the exception, but then I noticed that the VB TextFieldParser's exception does not include it.  I'm guessing that may be for security reasons.  For example, if you were parsing a file with sensitive data in it and didn't catch the exception, it might end up getting saved to an insecure logfile or something like that.

So the error line is not included in the exception both for compatibility and possible security reasons.  I'm not a huge fan of the class variable to provide access to the error line, but there are a lot of things I'd probably design differently if compatibility weren't a goal.

**Comment by Krakean** [comment]
@22222 can you please allow to include error line via some flag for example, if compatibility is concern? Would help much when testing.

**Comment by 22222** [comment]
No, I'd prefer to limit the configuration flags in this library as much as possible (especially outside of the ones already in the VB parser).

You can get the error line from the parser, like this:

```c#
CsvTextFieldParser parser;
try
{
	// Use the parser
}
catch (CsvMalformedLineException ex)
{
	// Log the line, throw a new exception that includes it, etc.
	Console.WriteLine(parser.ErrorLine);
	throw;
}
```

And otherwise everything does go through that `CreateMalformedLineException` method, so it should be pretty easy to add it directly to the exception if you end up using your own copy of this library.
