### ISSUE TITLE
Issue with line parsing

### ISSUE THREAD

**Issue by Krakean** [22222/CsvTextFieldParser#7]
Hello
Can you please add workaround for lines like this:
"=HYPERLINK(""http://www.theice.com/products/67445363"",""Coffee "C" Calendar Spread Option"")","4137","KC","KC","","","Coffee","Coffee C","ICUS","IFUS","Coffee C"
"=HYPERLINK(""http://www.theice.com/products/4210003"",""Weekly Coffee "C" Options"")","3731","KCW","KCW","","","Coffee","Coffee C","ICUS","IFUS","Coffee C"

I.e., when there is a quote inside the quote ("Weekly Coffee -->"C"<--- Options")
Currently its considered as malformed

**Comment by 22222** [comment]
That does appear to be correctly considered malformed CSV, both in this parser and the VB version.  Some of the double quotes are not escaped correctly.  From [RFC-4180](https://tools.ietf.org/html/rfc4180#page-3):

>   7.  If double-quotes are used to enclose fields, then a double-quote
>       appearing inside a field must be escaped by preceding it with
>       another double quote.  For example:
>
>       "aaa","b""bb","ccc"

In this example, the first field the parser would see is: 

```csv
"=HYPERLINK(""http://www.theice.com/products/67445363"",""Coffee "
```

To be valid CSV, the next non-whitespace character would have to be a comma.  But then next characters  are `C" Calendar Spread Option"")",`, so the exception is thrown for malformed input.  See the [error handling](https://github.com/22222/CsvTextFieldParser#error-handling) documentation for more details.
