### ISSUE TITLE
Error: is too long, or a component of the specified path is too long.

### ISSUE THREAD

**Issue by jshellis** [22222/CsvTextFieldParser#9]
Getting the error: is too long, or a component of the specified path is too long.
When parsing a CSV with 100,000 records and 30 columns.
Can you tell me what the limit on the string is?

**Comment by 22222** [comment]
Did you get around the error?

If not, I might be able to give some advice if you have the full stack trace from the error (or at least the parts of it that come from this library).

**Comment by jshellis** [comment]
I did the issue was passing the CSV as a string instead of stream. Thanks for the reply though :)
